Add security changes needed for docker
ubiqube/docs pull request #76
Opened 2021-06-24 09:28 UTC by efeubiqube

2021-06-24 11:25 UTC, ArnaudFosse approved these changes

2021-06-25 09:13 UTC, abr-ubiqube requested changes

2021-06-25 09:13 UTC, abr-ubiqube commented on doc-src/admin-guide/admin-guide-single.adoc
> +include::{includedir}/security_configuration.adoc[]
@efeubiqube 
this doc needs to be included after include::{includedir}/ha_installation.adoc[]

2021-06-25 09:13 UTC, abr-ubiqube commented on doc-src/admin-guide/security_configuration.adoc
> +:doctype: book
to be removed

2021-06-25 09:13 UTC, abr-ubiqube commented on doc-src/admin-guide/security_configuration.adoc
> +
add 
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

2021-06-25 09:13 UTC, abr-ubiqube commented on doc-src/admin-guide/security_configuration.adoc
> += Security Configuration
change to "Security Configuration for HA Setup"

2021-06-25 09:41 UTC, abr-ubiqube approved these changes

2021-06-30 08:36 UTC, merged